
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignIn, SignInButton, SignOutButton, SignUpButton, UserButton, } from "@clerk/nextjs";






const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (<ClerkProvider ><html lang="en">
    <body style={{ colour: "white", background: "black" }}


    >

      {children}
      <div>
        <SignedOut><SignInButton mode="redirect" /><br></br>
          <SignUpButton mode="redirect" /></SignedOut>


      </div>
    </body>
  </html>

  </ClerkProvider>






  );
}
