
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignIn, SignInButton, SignOutButton, SignUpButton, UserButton, } from "@clerk/nextjs";
import custSignIn from "@/components/custSignIn";
import DeleteAccount from "@/components/deletebutton";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (<ClerkProvider ><html lang="en">
    <body style={{ colour: "white", background: "black" }}>

      {children}
      <div className="flex justify-end gap-10 m-4">
        <SignedOut>
          <SignInButton mode="redirect">
            <button className="bg-green-500 hover:bg-green-300 font-bold text-sm px-4 py-2 rounded-md">
              Sign In
            </button>
          </SignInButton>

          <SignUpButton mode="redirect">
            <button className="bg-green-500 hover:bg-green-300 font-bold text-sm px-4 py-2 rounded-md">
              Sign UP
            </button>
          </SignUpButton>
        </SignedOut>
        <SignedIn ><UserButton /><br></br>
          <DeleteAccount /></SignedIn>


      </div>
    </body>
  </html>

  </ClerkProvider>






  );
}
